name: Main Branch Workflow

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  # Build and test
  build:
    uses: ./.github/workflows/build_and_test.yml

  release-1:
    uses: ./.github/workflows/release.yml
    needs: [build]
    with:
      projectPath: src/DynamicRoles.Core/DynamicRoles.Core.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  release-2:
    uses: ./.github/workflows/release.yml
    needs: [build]
    with:
      projectPath: src/DynamicRoles.Server/DynamicRoles.Server.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  release-3:
    uses: ./.github/workflows/release.yml
    needs: [build]
    with:
      projectPath: src/DynamicRoles.Blazor/DynamicRoles.Blazor.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  release-4:
    uses: ./.github/workflows/release.yml
    needs: [build]
    with:
      projectPath: src/DynamicRoles.Shared/DynamicRoles.Shared.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  release-5:
    uses: ./.github/workflows/release.yml
    needs: [build]
    with:
      projectPath: src/DynamicRoles.Tests/DynamicRoles.Tests.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}