### source https://lukelowrey.com/use-github-actions-to-publish-nuget-packages/

#
name: Release to NuGet.org

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore DynamicRoles.sln

      # Test
    - name: Build
      run: dotnet build DynamicRoles.sln --configuration Release --no-restore

      # Test
    - name: Test
      run: dotnet test DynamicRoles.sln --configuration Release --no-build --verbosity normal

      # Publish
    - name: Publish DynamicRoles.Core
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/DynamicRoles.Core/DynamicRoles.Core.csproj
          INCLUDE_SYMBOLS: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish DynamicRoles.Server
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/DynamicRoles.Server/DynamicRoles.Server.csproj
          INCLUDE_SYMBOLS: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish DynamicRoles.Blazor
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/DynamicRoles.Blazor/DynamicRoles.Blazor.csproj
          INCLUDE_SYMBOLS: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Publish DynamicRoles.Tests
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/DynamicRoles.Tests/DynamicRoles.Tests.csproj
          INCLUDE_SYMBOLS: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}