name: Release to NuGet.org

on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
      projectPath:
        required: true
        type: string
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Publish ${{ inputs.projectName }}
      uses: alirezanet/publish-nuget@v3.0.0
      with:
          PROJECT_FILE_PATH: ${{ inputs.projectPath }}
          INCLUDE_SYMBOLS: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}