name: Release to NuGet.org

on:
  workflow_call:
    inputs:
      projectPath:
        required: true
        type: string
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    # NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    # NET Standard
    - name: Setup .NET Standard
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x

    # Restore Dependencies
    - name: Restore dependencies
      run: dotnet restore DynamicRoles.sln

    # Build
    - name: Build
      run: dotnet build DynamicRoles.sln --configuration Release --no-restore

    # Publish
    - name: Publish to NuGet
      uses: alirezanet/publish-nuget@v3.0.0
      with:
          PROJECT_FILE_PATH: ${{ inputs.projectPath }}
          INCLUDE_SYMBOLS: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}